apiVersion: v1
data:
  username: YWRtaW4=
  password: MWYyZDFlMmU2N2Rm
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: { ... }
  creationTimestamp: 2020-01-22T18:41:56Z
  name: mysecret-test
  namespace: default
  resourceVersion: "164619"
  uid: cfee02d6-c137-11e5-8d73-42010af00002
type: Opaque



apiVersion: v2
name: bigbang
version: 1.39.0
description: Big Bang is a declarative, continuous delivery tool for core DoD hardened and approved packages into a Kubernetes cluster.

type: application

keywords:
  - platform1
  - bigbang

home: https://p1.dso.mil/#/products/big-bang
sources:
  - https://repo1.dso.mil/platform-one/big-bang/bigbang

maintainers:
  - name: Ryan Garcia
    email: garcia.ryan@solute.us
  - name: Michael McLeroy
    email: michaelmcleroy@cloudfitsoftware.com
  - name: Micah Nagel
    email: micah.nagel@parsons.com
  - name: Branden Cobb
    email: cobb_branden@bah.com
  - name: Tom Runyon
    email: tom@defenseunicorns.com

icon: https://p1.dso.mil/img/Big_Bang_Color_Logo_White_text.b04263b1.png
